# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'
            Symfony\Component\Messenger\MessageBusInterface $eventBus: '@event.bus'

    App\:
        resource: '../src/Kernel.php'

    Shared\:
        resource: '../src/Shared/'
        exclude:
            - '../src/Shared/Domain/'
            - '../src/Shared/Infrastructure/Kernel/'

    Identity\:
        resource: '../src/Identity/'
        exclude:
            - '../src/Identity/Domain/'

    Profile\:
        resource: '../src/Profile/'
        exclude:
            - '../src/Profile/Domain/'

    Medication\:
        resource: '../src/Medication/'
        exclude:
            - '../src/Medication/Domain/'

    Schedule\:
        resource: '../src/Schedule/'
        exclude:
            - '../src/Schedule/Domain/'

    DoseEvent\:
        resource: '../src/DoseEvent/'
        exclude:
            - '../src/DoseEvent/Domain/'

    Notification\:
        resource: '../src/Notification/'
        exclude:
            - '../src/Notification/Domain/'

    CalendarIntegration\:
        resource: '../src/CalendarIntegration/'
        exclude:
            - '../src/CalendarIntegration/Domain/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
