<?php

declare(strict_types=1);

namespace CalendarIntegration\Domain;

interface CalendarGateway
{
    /**
     * Creates or updates an event on the user's calendar.
     *
     * @param string $refreshToken Encryption-vaulted refresh token for OAuth
     * @param string $title Event title
     * @param \DateTimeImmutable $start Event start date/time
     * @param \DateTimeImmutable $end Event end date/time
     * @param string $description Description
     * @return string The external event ID generated by the calendar provider
     */
    public function upsertEvent(
        string $refreshToken,
        string $title,
        \DateTimeImmutable $start,
        \DateTimeImmutable $end,
        string $description
    ): string;

    /**
     * Deletes an event from the user's calendar.
     *
     * @param string $refreshToken Encryption-vaulted refresh token for OAuth
     * @param string $externalEventId The ID of the event to delete
     */
    public function deleteEvent(string $refreshToken, string $externalEventId): void;
}
