<?php

declare(strict_types=1);

namespace CalendarIntegration\Domain;

interface CalendarGateway
{
    /**
     * Creates or updates an event on the user's calendar.
     *
     * @param string $accessToken Short-lived provider access token
     * @param string $title Event title
     * @param \DateTimeImmutable $start Event start date/time
     * @param \DateTimeImmutable $end Event end date/time
     * @param string $description Description
     * @param string|null $externalEventId Existing provider event ID, when updating
     * @return string The external event ID generated by the calendar provider
     */
    public function upsertEvent(
        string $accessToken,
        string $title,
        \DateTimeImmutable $start,
        \DateTimeImmutable $end,
        string $description,
        ?string $externalEventId = null,
        ?string $idempotencyKey = null
    ): string;

    /**
     * Deletes an event from the user's calendar.
     *
     * @param string $accessToken Short-lived provider access token
     * @param string $externalEventId The ID of the event to delete
     */
    public function deleteEvent(string $accessToken, string $externalEventId): void;
}
